name: ai_chat_app
description: A simple Flutter AI chat app powered by OpenAI.
publish_to: 'none'
version: 1.2.16+18

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cryptography: ^2.7.0
  crypto: ^3.0.3
  http: ^1.1.0
  cached_network_image: ^3.2.3
  desktop_drop: ^0.4.4
  file_picker: ^8.0.7
  http_parser: ^4.0.2
  image: ^4.2.0
  path_provider: ^2.1.0
  path: ^1.8.0
  sqflite_common_ffi: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/branding/
    - assets/prompt_templates/

hooks:
  user_defines:
    sqlite3:
      source: system
      name_windows: winsqlite3
      name: sqlite3
